spring:
  application:
    name: zuul-server
server:
  port: 3000
  address: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1000/eureka/
    enabled: true
  instance:
    hostname: ${server.address}

zuul:
  routes:
    user:
      path: /api/user/**
      service-id: micro-service-user
    product:
      path: /api/product/**
      service-id: micro-service-product
    addr:
      path: /api/addr/**
      service-id: micro-service-addr
    cart:
      path: /api/cart/**
      service-id: micro-service-cart
    order:
      path: /api/order/**
      service-id: micro-service-order
  ignored-services: '*'
  sensitive-headers:

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000